

####################################
### Section - 7, Key TFs & genes ###
####################################

### Here, we present an example - HSCs, showing much heterogeneity even at the progenitor state
### How it connects to multiple different derivatives?

source("JAX_help_code.R")
source("JAX_color_code.R")
work_path = "./"

pd_all = readRDS(paste0(work_path, "df_cell_graph.rds"))
rownames(pd_all) = as.vector(pd_all$cell_id)

nodes = read.table(paste0(work_path, "nodes.txt"), header=T, as.is=T, sep="\t")

celltype_include = c("Hematopoietic stem cells (Cd34+)")
example_i = "HSC"

pd_sub = pd_all[pd_all$celltype_new %in% celltype_include,]
mouse_gene_sub = mouse_gene[(mouse_gene$gene_type %in% c('protein_coding', 'pseudogene', 'lincRNA')) & mouse_gene$chr %in% paste0("chr", c(1:19, "M")),]
gene_count = doExtractData(pd_sub, mouse_gene_sub)

writeMM(t(gene_count), paste0(work_path, example_i, ".gene_count.mtx"))
write.csv(pd, paste0(work_path, example_i, ".df_cell.csv"))


### Using Scanpy to perform cell embedding
### python HSCs_progenitors.py

pd_x = read.csv(paste0(work_path, example_i, "_adata_scale.obs.csv"), header=T, row.names=1, as.is=T)

x_table = table(pd_x$day)
pd_1 = pd_x[pd_x$day %in% names(x_table)[x_table > 1000],]
pd_1_ = pd_1 %>% group_by(day) %>% sample_n(1000)
pd_1 = pd_1[pd_1$cell_id %in% pd_1_$cell_id,]
pd_2 = pd_x[pd_x$day %in% names(x_table)[x_table <= 1000],]
pd_plot = rbind(pd_1, pd_2)
pd_plot$day = factor(pd_plot$day, levels = names(day_color_plate))

### Extended Data Fig. 11p

p = ggplot() +
    geom_point(data = pd_plot, aes(x = UMAP_2d_1, y = UMAP_2d_2), size=1) +
    geom_point(data = pd_plot[sample(1:nrow(pd_plot)),], aes(x = UMAP_2d_1, y = UMAP_2d_2, color = day), size=0.8) +
    theme_void() +
    scale_color_manual(values=day_color_plate) +
    theme(legend.position="none") + 
    ggsave(paste0(work_path, example_i, ".day.png"), width = 6, height = 6, dpi = 300)




##################################################################
### what are the MNNs between HSCs and its multiple derivatives ##
##################################################################

example_i = "HSC"
system_i = "Blood"

pd_target = read.csv(paste0(work_path, example_i, "_adata_scale.obs.csv"), header=T, row.names=1, as.is=T)

### Of note, this profile is generated by co-embedding all the cell types of Blood system
### Please see the scripts from Section_6_development_tree for details
pd = readRDS(paste0(work_path, system_i, "_adata_scale.obs.csv"), header=T, row.names=1, as.is=T)
pd_all = readRDS(paste0(work_path, "df_cell_graph.rds"))
pd$celltype_new = NULL
pd = pd %>% left_join(pd_all[,c("cell_id", "celltype_new")], by = "cell_id")
nodes = read.table(paste0(work_path, "nodes.txt"), header=T, as.is=T, sep="\t")

if ("meta_group" %in% names(pd)) {pd$meta_group = NULL}
pd_x = pd %>% left_join(nodes %>% filter(system == system_i) %>% select(celltype_new, meta_group))
pd$meta_group = as.vector(pd_x$meta_group)

y = data.frame(i = 1:nrow(pd),
               j = 1:nrow(pd),
               meta_group = as.vector(pd$meta_group), 
               cell_id = as.vector(pd$cell_id), stringsAsFactors = FALSE)

### Of note, this profile is generated by identifying MNN pairs of cells within Blood system
### Please see the scripts from Section_6_development_tree for details
x = readRDS(paste0(work_path, system_i, ".MNN.rds"))
x_rev = x
x_rev$i = x$j
x_rev$j = x$i
x_rev = rbind(x, x_rev)
dat = x_rev %>% left_join(y %>% select(i, meta_group, cell_id), by = "i") %>%
    left_join(y %>% select(j, meta_group, cell_id), by = "j")

edges = read.table(paste0(work_path, "edges.txt"), as.is=T, sep="\t")
nodes_include = as.vector(edges$V3[edges$V2 == "B_M11"])

dat_uniq = dat %>% filter(meta_group.x == "B_M11", meta_group.y %in% nodes_include) %>%
    group_by(cell_id.x, meta_group.y) %>% tally() %>% 
    group_by(cell_id.x) %>% slice_max(order_by = n, n = 1, with_ties = F) %>% 
    rename(cell_id = cell_id.x, meta_group = meta_group.y) %>% select(cell_id, meta_group) %>%
    left_join(nodes[,c("meta_group", "celltype_new")]) %>% rename(MNN = celltype_new)

pd_target = pd_target %>% left_join(dat_uniq[,c("cell_id","MNN")])

### Extended Data Fig. 11q

p = ggplot() +
    geom_point(data = pd_target[is.na(pd_target$MNN),], aes(x = UMAP_2d_1, y = UMAP_2d_2), color = "grey80", size=0.6) +
    geom_point(data = pd_target[!is.na(pd_target$MNN),], aes(x = UMAP_2d_1, y = UMAP_2d_2), size=0.65) +
    geom_point(data = pd_target[!is.na(pd_target$MNN),], aes(x = UMAP_2d_1, y = UMAP_2d_2, color = MNN), size=0.6) +
    theme_void() +
    scale_color_manual(values=blood_system_color_plate) +
    theme(legend.position="none") + 
    ggsave(paste0(work_path, example_i, ".MNN.png"), width = 6, height = 6, dpi = 300)

